import { env } from '$env/dynamic/private';

export interface AppConfig {
	APP_PORT: number;
	REMNAWAVE_PANEL_URL: string;
	REMNAWAVE_API_TOKEN: string;
	SUBPAGE_CONFIG_UUID: string;
	CUSTOM_SUB_PREFIX: string;
	INTERNAL_JWT_SECRET: string;
	CADDY_AUTH_API_TOKEN?: string;
	CLOUDFLARE_ZERO_TRUST_CLIENT_ID?: string;
	CLOUDFLARE_ZERO_TRUST_CLIENT_SECRET?: string;
	EGAMES_COOKIE?: string;
}

export function getAppConfig(): AppConfig {
	return {
		APP_PORT: parseInt(env.APP_PORT || '3010', 10),
		REMNAWAVE_PANEL_URL: env.REMNAWAVE_PANEL_URL || '',
		REMNAWAVE_API_TOKEN: env.REMNAWAVE_API_TOKEN || '',
		SUBPAGE_CONFIG_UUID: env.SUBPAGE_CONFIG_UUID || '00000000-0000-0000-0000-000000000000',
		CUSTOM_SUB_PREFIX: env.CUSTOM_SUB_PREFIX || '',
		INTERNAL_JWT_SECRET: env.INTERNAL_JWT_SECRET || 'default-internal-jwt-secret-nya-1234567890',
		CADDY_AUTH_API_TOKEN: env.CADDY_AUTH_API_TOKEN,
		CLOUDFLARE_ZERO_TRUST_CLIENT_ID: env.CLOUDFLARE_ZERO_TRUST_CLIENT_ID,
		CLOUDFLARE_ZERO_TRUST_CLIENT_SECRET: env.CLOUDFLARE_ZERO_TRUST_CLIENT_SECRET,
		EGAMES_COOKIE: env.EGAMES_COOKIE
	};
}
